version: "3.8"

services:
  web:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - 80:80
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=django_user
      - POSTGRES_PASSWORD=django_password
      - POSTGRES_DB=django_database

volumes:
  postgres_data:
