region = "us-west-2"
project_name = "fullstack-web-app-template"
gh_personal_access_token = "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"
gh_repository = "https://github.com/imranmatin23/fullstack-web-app-template"
domain_name = "imranmatin.com"
sub_domain_prefix = "template"
backend_url = "https://api.template.imranmatin.com"
