name: Push to Amazon ECR and deploy to Amazon ECS using Terraform Apply
run-name: ${{ github.sha }}

on:
  push:
    branches: ["main"]

env:
  AWS_REGION: us-west-2
  ECR_REPOSITORY: fullstack-web-app-template-backend

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # https://aws.amazon.com/blogs/security/use-iam-roles-to-connect-github-actions-to-actions-in-aws/
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::775627766428:role/ecr-image-push-role
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}

      # - name: Login to Amazon ECR
      #   id: login-ecr
      #   uses: aws-actions/amazon-ecr-login@v1

      # - name: Build, tag, and push image to Amazon ECR
      #   id: build-image
      #   env:
      #     ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      #     IMAGE_TAG: latest
      #   run: |
      #     # Build a docker container and push it to ECR
      #     cd backend
      #     docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
      #     docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
      #     echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: |
          cd infra/backend
          terraform init

      # generate Terraform Plan and store in .tfplan file
      - name: Terraform Plan
        run: |
          cd infra/backend
          terraform plan -out terraform.tfplan

      # apply previously generated Terraform Plan
      # from the terraform.tfplan file in the branch
      - name: Terraform Apply
        run: |
          cd infra/backend
          terraform apply "terraform.tfplan"
