name: Deploy Backend Infrastructure
run-name: ${{ github.sha }}

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - infra/backend/**

env:
  AWS_REGION: us-west-2
  TF_VAR_secret_key: ${{ secrets.BACKEND_INFRA_SECRET_KEY }}

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infra/backend

    steps:
      # Clone the Repository
      - name: Checkout
        uses: actions/checkout@v3

      # Generate temporary AWS credentials by assuming a role (https://aws.amazon.com/blogs/security/use-iam-roles-to-connect-github-actions-to-actions-in-aws/)
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::775627766428:role/ecr-image-push-role
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: |
          terraform init

      - name: Terraform Plan
        run: |
          terraform plan -no-color -input=false -var-file prod.tfvars

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve -input=false -var-file prod.tfvars
